"""Add missing Trip fields

Revision ID: 55b199b51a02
Revises: cdf1d66603b2
Create Date: 2026-10-01 19:53:18.273250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b199b51a02'
down_revision: Union[str, Sequence[str], None] = 'cdf1d66603b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('budget', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('spent', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('trips', sa.Column('weather_temp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'weather_temp')
    op.drop_column('trips', 'image_url')
    op.drop_column('trips', 'spent')
    op.drop_column('trips', 'budget')
    # ### end Alembic commands ###
