"""Rename expense description to title

Revision ID: 5d37ba968602
Revises: 55b199b51a02
Create Date: 2026-10-01 20:25:22.845013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d37ba968602'
down_revision: Union[str, Sequence[str], None] = '55b199b51a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('expenses', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('expenses', 'title')
    # ### end Alembic commands ###
